//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyStatusReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dailyStatusReportData
    {
        public int StatusID { get; set; }
        public string DeveloperName { get; set; }
        public string FixVersion { get; set; }
        public string Project { get; set; }
        public int TicketNumber { get; set; }
        public string TicketDescription { get; set; }
        public string TicketStatus { get; set; }
        public string CrucibleId { get; set; }
        public string Remark { get; set; }
        public string Blocker { get; set; }
    }
}
